server:
  port: ${PORT:8761}

profiles:
  active: ${ARCH_ENV:peer}

eureka:
  instance:
    hostname: ${DOMAIN:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_PEER_URL}/eureka/
